import AppKit
import ClipMintCore

/// Polls NSPasteboard.general (there is no change notification on macOS) and reports new content.
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()
    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    weak var state: AppState?

    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    func start(state: AppState) {
        self.state = state
        lastChangeCount = NSPasteboard.general.changeCount
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in self?.poll() }
        timer?.tolerance = 0.1
        RunLoop.main.add(timer!, forMode: .common)
    }

    /// Call right after ClipMint itself writes to the pasteboard.
    func ignoreCurrentChange() { lastChangeCount = NSPasteboard.general.changeCount }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard let state else { return }
        let types = Set(pb.types ?? [])
        if types.contains(Self.concealed) || types.contains(Self.transient) || types.contains(Self.autoGenerated) { return }

        let front = NSWorkspace.shared.frontmostApplication
        let bundle = front?.bundleIdentifier
        if let bundle, Prefs.ignoredApps.contains(bundle) { return }
        if bundle == Bundle.main.bundleIdentifier { return }
        let appName = front?.localizedName
        let now = Date()

        // Files
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }
            let clip = Clip(kind: .file, text: paths.map { ($0 as NSString).lastPathComponent }.joined(separator: "\n"), filePaths: paths,
                            sourceApp: bundle, sourceAppName: appName, createdAt: now, lastUsedAt: now, hash: TextTools.contentHash("files:" + paths.joined(separator: "|")))
            state.ingest(clip, imageData: nil, rtf: nil)
            return
        }
        // Images (prefer PNG; convert TIFF/others)
        if types.contains(.png) || types.contains(.tiff) {
            var png = pb.data(forType: .png)
            if png == nil, let img = NSImage(pasteboard: pb) { png = Storage.pngData(from: img) }
            if let png, png.count < 25_000_000 {
                let clip = Clip(kind: .image, text: "", sourceApp: bundle, sourceAppName: appName, createdAt: now, lastUsedAt: now,
                                hash: TextTools.contentHash(bytes: png))
                state.ingest(clip, imageData: png, rtf: nil)
                return
            }
        }
        // Text
        guard let str = pb.string(forType: .string), !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard str.utf8.count < 2_000_000 else { return }
        let kind: ClipKind = TextTools.isURL(str) ? .link : (TextTools.hexColor(in: str) != nil ? .color : .text)
        let rtf = pb.data(forType: .rtf)
        let clip = Clip(kind: kind, text: str, sourceApp: bundle, sourceAppName: appName, createdAt: now, lastUsedAt: now, hash: TextTools.contentHash(str))
        state.ingest(clip, imageData: nil, rtf: rtf)
    }
}
